### ISSUE TITLE
arabic_reshape() is not working as it should

### ISSUE THREAD

**Issue by nomad-scl** [sigmaSd/arabic-reshaper-rs#3]
while trying to put and arabic string in "arabic_reshape()" it doesn't reshape the arabic text correctly, following is the code I used in both windows 7 and windows 10:

```
println!("{}", arabic_reshaper::arabic_reshape("السلام عليكم"));
println!("{}", arabic_reshaper::arabic_reshape("حسين"));
println!("{}", arabic_reshaper::arabic_reshape(&*"السلام عليكم".chars().rev().collect::<String>()));
println!("{}", arabic_reshaper::arabic_reshape(&*"حسين".chars().rev().collect::<String>()));
```

and this is the output in terminal
ﻣﻜﻴﻠﻊ ﻣﺎﻟﺴﻼ
ﻧﻴﺴﺢ

also I tried to use the above code to edit an image and add an arabic text with the same problem

**Comment by sigmaSd** [comment]
Hello,

This library only does the reshaping  (as in render the correct ligature) , but it doesn't reverse the letters.

Reversing the letters is done via http://unicode.org/reports/tr9/

For simple cases, you can do `.rev()` the problem with your attempt is that you reversed the letters before reshaping.

The correct way to do this would be 
`println!("{}", arabic_reshaper::arabic_reshape(&*"حسين").chars().rev().collect::<String>());`       (the `)` position has changed)

Also checkout https://github.com/NightMachinary/rtl_reshaper_rs/blob/master/src/main.rs for an example of such usage.

I can see that the README example is misleading, I'll update it.

**Comment by sigmaSd** [comment]
https://github.com/sigmaSd/arabic-reshaper-rs/commit/aa32e5a3e880747e1b56463c35891d912814a6e2

**Comment by nomad-scl** [comment]
thanks, it worked, I'm going to close this issue now
you should include the reversing in the example in the md page
also is there a reason you can't return the text reversed

**Comment by sigmaSd** [comment]
Reshaping and reversing the letters are different problems, this crate solve the first one, crates like `unic_bidi` solves the second problem. Mixing the 2 crates is very straightforward though.

I see your point that examples are missing, I'll adress that issue when I can.
